services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_MULTIPLE_DATABASES: car_db, user_db, purshcase_db, sale_db, auth_db
      - POSTGRES_PASSWORD: 12345
      - POSTGRES_USER: postgres
    ports:
      - '5432'
